disallowed-methods = [
  "<[u8]>::rsplit",
  "<[u8]>::split",
  "alloc::sync::Arc",
  "core::str::from_utf8",
  "core::sync::atomic::AtomicU32",
  "core::sync::atomic::AtomicU64",
  "core::sync::atomic::AtomicUsize",
  "core::sync::atomic::Ordering",
  "core::sync::atomic::fence",
  "str::rsplit",
]
disallowed-types = [
  "std::collections::HashMap",
  "std::collections::HashSet"
]
doc-valid-idents = [
  "MiB",
  "PostgreSQL",
  "WebSocket",
  "WebSockets",
  "WebTransport"
]
too-many-arguments-threshold = 10
type-complexity-threshold = 500
