cognitive-complexity-threshold = 50
disallowed-methods = [
  "char::encode_utf8",
  "core::str::from_utf8",
  "core::sync::atomic::fence",
  "slice::rsplit",
  "slice::split",
  "str::rsplit",
]
disallowed-types = [
  "alloc::sync::Arc",
  "core::sync::atomic::AtomicU32",
  "core::sync::atomic::AtomicU64",
  "core::sync::atomic::AtomicUsize",
  "std::collections::HashMap",
  "std::collections::HashSet"
]
doc-valid-idents = [
  "MiB",
  "PostgreSQL",
  "WebSocket",
  "WebSockets",
  "WebTransport"
]
too-many-arguments-threshold = 16
type-complexity-threshold = 500
