mod certificate_revocation_list;
pub mod cipher_suite;
mod client_hello;
mod client_verifier;
mod crypto_sets;
mod de;
mod extension_ty;
mod extensions;
mod max_fragment_length;
mod misc;
mod named_group;
mod revocation_reason;
mod revoked_certificate;
mod server_verifier;
mod signature_scheme;
mod signed_certificate_data;
mod state;
mod structs;
mod tls_acceptor;
mod tls_buffer;
mod tls_config;
mod tls_connector;
mod tls_error;
mod tls_mode;
mod tls_stream;
mod trust_anchor;

pub use certificate_revocation_list::CertificateRevocationList;
pub use client_verifier::ClientVerifier;
pub use crypto_sets::{AwsLc, Ring, Openssl, RustCrypto};
pub use max_fragment_length::MaxFragmentLength;
pub use named_group::NamedGroup;
pub use revocation_reason::RevocationReasonCode;
pub use revoked_certificate::RevokedCertificate;
pub use server_verifier::ServerVerifier;
pub use signature_scheme::SignatureScheme;
pub use signed_certificate_data::SignedCertificateData;
pub use tls_acceptor::TlsAcceptor;
pub use tls_buffer::TlsBuffer;
pub use tls_config::TlsConfig;
pub use tls_connector::TlsConnector;
pub use tls_error::TlsError;
pub use tls_mode::*;
pub use tls_stream::TlsStream;
pub use trust_anchor::TrustAnchor;

/// Identifier of a certificate
pub type SerialNumber = crate::collection::ArrayVectorU8<u8, 20>;
