#![expect(
  clippy::allow_attributes_without_reason,
  clippy::arithmetic_side_effects,
  clippy::indexing_slicing,
  non_camel_case_types,
  unreachable_pub,
  unsafe_op_in_unsafe_fn,
  unused,
  reason = "generated code"
)]

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
  #[inline]
  pub const fn new() -> Self {
    __IncompleteArrayField(::core::marker::PhantomData, [])
  }
  #[inline]
  pub const fn as_ptr(&self) -> *const T {
    let ptr_self: *const Self = self;
    let ptr_ty: *const T = ptr_self.cast();
    ptr_ty
  }
  #[inline]
  pub const fn as_mut_ptr(&mut self) -> *mut T {
    let ptr_self: *mut Self = self;
    let ptr_ty: *mut T = ptr_self.cast();
    ptr_ty
  }
  #[inline]
  pub const unsafe fn as_slice(&self, len: usize) -> &[T] {
    ::core::slice::from_raw_parts(self.as_ptr(), len)
  }
  #[inline]
  pub const unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
    ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
  }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    f.write_str("__IncompleteArrayField")
  }
}
pub const __BITS_PER_LONG: u32 = 64;
pub const __BITS_PER_LONG_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const TLS_TX: u32 = 1;
pub const TLS_RX: u32 = 2;
pub const TLS_TX_ZEROCOPY_RO: u32 = 3;
pub const TLS_RX_EXPECT_NO_PAD: u32 = 4;
pub const TLS_TX_MAX_PAYLOAD_LEN: u32 = 5;
pub const TLS_1_2_VERSION_MAJOR: u32 = 3;
pub const TLS_1_2_VERSION_MINOR: u32 = 3;
pub const TLS_1_3_VERSION_MAJOR: u32 = 3;
pub const TLS_1_3_VERSION_MINOR: u32 = 4;
pub const TLS_CIPHER_AES_GCM_128: u32 = 51;
pub const TLS_CIPHER_AES_GCM_128_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_AES_GCM_128_KEY_SIZE: u32 = 16;
pub const TLS_CIPHER_AES_GCM_128_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_AES_GCM_128_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_AES_GCM_128_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_AES_GCM_256: u32 = 52;
pub const TLS_CIPHER_AES_GCM_256_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_AES_GCM_256_KEY_SIZE: u32 = 32;
pub const TLS_CIPHER_AES_GCM_256_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_AES_GCM_256_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_AES_GCM_256_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_AES_CCM_128: u32 = 53;
pub const TLS_CIPHER_AES_CCM_128_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_AES_CCM_128_KEY_SIZE: u32 = 16;
pub const TLS_CIPHER_AES_CCM_128_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_AES_CCM_128_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_AES_CCM_128_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_CHACHA20_POLY1305: u32 = 54;
pub const TLS_CIPHER_CHACHA20_POLY1305_IV_SIZE: u32 = 12;
pub const TLS_CIPHER_CHACHA20_POLY1305_KEY_SIZE: u32 = 32;
pub const TLS_CIPHER_CHACHA20_POLY1305_SALT_SIZE: u32 = 0;
pub const TLS_CIPHER_CHACHA20_POLY1305_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_CHACHA20_POLY1305_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_SM4_GCM: u32 = 55;
pub const TLS_CIPHER_SM4_GCM_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_SM4_GCM_KEY_SIZE: u32 = 16;
pub const TLS_CIPHER_SM4_GCM_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_SM4_GCM_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_SM4_GCM_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_SM4_CCM: u32 = 56;
pub const TLS_CIPHER_SM4_CCM_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_SM4_CCM_KEY_SIZE: u32 = 16;
pub const TLS_CIPHER_SM4_CCM_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_SM4_CCM_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_SM4_CCM_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_ARIA_GCM_128: u32 = 57;
pub const TLS_CIPHER_ARIA_GCM_128_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_ARIA_GCM_128_KEY_SIZE: u32 = 16;
pub const TLS_CIPHER_ARIA_GCM_128_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_ARIA_GCM_128_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_ARIA_GCM_128_REC_SEQ_SIZE: u32 = 8;
pub const TLS_CIPHER_ARIA_GCM_256: u32 = 58;
pub const TLS_CIPHER_ARIA_GCM_256_IV_SIZE: u32 = 8;
pub const TLS_CIPHER_ARIA_GCM_256_KEY_SIZE: u32 = 32;
pub const TLS_CIPHER_ARIA_GCM_256_SALT_SIZE: u32 = 4;
pub const TLS_CIPHER_ARIA_GCM_256_TAG_SIZE: u32 = 16;
pub const TLS_CIPHER_ARIA_GCM_256_REC_SEQ_SIZE: u32 = 8;
pub const TLS_SET_RECORD_TYPE: u32 = 1;
pub const TLS_GET_RECORD_TYPE: u32 = 2;
pub const TLS_CONF_BASE: u32 = 1;
pub const TLS_CONF_SW: u32 = 2;
pub const TLS_CONF_HW: u32 = 3;
pub const TLS_CONF_HW_RECORD: u32 = 4;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
  pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of __kernel_fd_set"][::core::mem::size_of::<__kernel_fd_set>() - 128usize];
  let _ = ["Alignment of __kernel_fd_set"][::core::mem::align_of::<__kernel_fd_set>() - 8usize];
  let _ = ["Offset of field: __kernel_fd_set::fds_bits"]
    [::core::mem::offset_of!(__kernel_fd_set, fds_bits) - 0usize];
};
pub type __kernel_sighandler_t =
  ::core::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_dev_t = ::std::os::raw::c_ulong;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
  pub val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of __kernel_fsid_t"][::core::mem::size_of::<__kernel_fsid_t>() - 8usize];
  let _ = ["Alignment of __kernel_fsid_t"][::core::mem::align_of::<__kernel_fsid_t>() - 4usize];
  let _ = ["Offset of field: __kernel_fsid_t::val"]
    [::core::mem::offset_of!(__kernel_fsid_t, val) - 0usize];
};
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = ::std::os::raw::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __s128 = i128;
pub type __u128 = u128;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls_crypto_info {
  pub version: __u16,
  pub cipher_type: __u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls_crypto_info"][::core::mem::size_of::<tls_crypto_info>() - 4usize];
  let _ = ["Alignment of tls_crypto_info"][::core::mem::align_of::<tls_crypto_info>() - 2usize];
  let _ = ["Offset of field: tls_crypto_info::version"]
    [::core::mem::offset_of!(tls_crypto_info, version) - 0usize];
  let _ = ["Offset of field: tls_crypto_info::cipher_type"]
    [::core::mem::offset_of!(tls_crypto_info, cipher_type) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_aes_gcm_128 {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 16usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_aes_gcm_128"]
    [::core::mem::size_of::<tls12_crypto_info_aes_gcm_128>() - 40usize];
  let _ = ["Alignment of tls12_crypto_info_aes_gcm_128"]
    [::core::mem::align_of::<tls12_crypto_info_aes_gcm_128>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_128::info"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_128, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_128::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_128, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_128::key"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_128, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_128::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_128, salt) - 28usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_128::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_128, rec_seq) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_aes_gcm_256 {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 32usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_aes_gcm_256"]
    [::core::mem::size_of::<tls12_crypto_info_aes_gcm_256>() - 56usize];
  let _ = ["Alignment of tls12_crypto_info_aes_gcm_256"]
    [::core::mem::align_of::<tls12_crypto_info_aes_gcm_256>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_256::info"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_256, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_256::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_256, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_256::key"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_256, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_256::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_256, salt) - 44usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_gcm_256::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_gcm_256, rec_seq) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_aes_ccm_128 {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 16usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_aes_ccm_128"]
    [::core::mem::size_of::<tls12_crypto_info_aes_ccm_128>() - 40usize];
  let _ = ["Alignment of tls12_crypto_info_aes_ccm_128"]
    [::core::mem::align_of::<tls12_crypto_info_aes_ccm_128>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_ccm_128::info"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_ccm_128, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_ccm_128::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_ccm_128, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_ccm_128::key"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_ccm_128, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_ccm_128::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_ccm_128, salt) - 28usize];
  let _ = ["Offset of field: tls12_crypto_info_aes_ccm_128::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_aes_ccm_128, rec_seq) - 32usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct tls12_crypto_info_chacha20_poly1305 {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 12usize],
  pub key: [::std::os::raw::c_uchar; 32usize],
  pub salt: __IncompleteArrayField<::std::os::raw::c_uchar>,
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_chacha20_poly1305"]
    [::core::mem::size_of::<tls12_crypto_info_chacha20_poly1305>() - 56usize];
  let _ = ["Alignment of tls12_crypto_info_chacha20_poly1305"]
    [::core::mem::align_of::<tls12_crypto_info_chacha20_poly1305>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_chacha20_poly1305::info"]
    [::core::mem::offset_of!(tls12_crypto_info_chacha20_poly1305, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_chacha20_poly1305::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_chacha20_poly1305, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_chacha20_poly1305::key"]
    [::core::mem::offset_of!(tls12_crypto_info_chacha20_poly1305, key) - 16usize];
  let _ = ["Offset of field: tls12_crypto_info_chacha20_poly1305::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_chacha20_poly1305, salt) - 48usize];
  let _ = ["Offset of field: tls12_crypto_info_chacha20_poly1305::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_chacha20_poly1305, rec_seq) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_sm4_gcm {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 16usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_sm4_gcm"]
    [::core::mem::size_of::<tls12_crypto_info_sm4_gcm>() - 40usize];
  let _ = ["Alignment of tls12_crypto_info_sm4_gcm"]
    [::core::mem::align_of::<tls12_crypto_info_sm4_gcm>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_gcm::info"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_gcm, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_gcm::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_gcm, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_gcm::key"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_gcm, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_gcm::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_gcm, salt) - 28usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_gcm::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_gcm, rec_seq) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_sm4_ccm {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 16usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_sm4_ccm"]
    [::core::mem::size_of::<tls12_crypto_info_sm4_ccm>() - 40usize];
  let _ = ["Alignment of tls12_crypto_info_sm4_ccm"]
    [::core::mem::align_of::<tls12_crypto_info_sm4_ccm>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_ccm::info"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_ccm, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_ccm::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_ccm, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_ccm::key"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_ccm, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_ccm::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_ccm, salt) - 28usize];
  let _ = ["Offset of field: tls12_crypto_info_sm4_ccm::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_sm4_ccm, rec_seq) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_aria_gcm_128 {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 16usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_aria_gcm_128"]
    [::core::mem::size_of::<tls12_crypto_info_aria_gcm_128>() - 40usize];
  let _ = ["Alignment of tls12_crypto_info_aria_gcm_128"]
    [::core::mem::align_of::<tls12_crypto_info_aria_gcm_128>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_128::info"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_128, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_128::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_128, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_128::key"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_128, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_128::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_128, salt) - 28usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_128::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_128, rec_seq) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tls12_crypto_info_aria_gcm_256 {
  pub info: tls_crypto_info,
  pub iv: [::std::os::raw::c_uchar; 8usize],
  pub key: [::std::os::raw::c_uchar; 32usize],
  pub salt: [::std::os::raw::c_uchar; 4usize],
  pub rec_seq: [::std::os::raw::c_uchar; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  let _ = ["Size of tls12_crypto_info_aria_gcm_256"]
    [::core::mem::size_of::<tls12_crypto_info_aria_gcm_256>() - 56usize];
  let _ = ["Alignment of tls12_crypto_info_aria_gcm_256"]
    [::core::mem::align_of::<tls12_crypto_info_aria_gcm_256>() - 2usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_256::info"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_256, info) - 0usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_256::iv"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_256, iv) - 4usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_256::key"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_256, key) - 12usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_256::salt"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_256, salt) - 44usize];
  let _ = ["Offset of field: tls12_crypto_info_aria_gcm_256::rec_seq"]
    [::core::mem::offset_of!(tls12_crypto_info_aria_gcm_256, rec_seq) - 48usize];
};
pub const TLS_INFO_UNSPEC: _bindgen_ty_1 = 0;
pub const TLS_INFO_VERSION: _bindgen_ty_1 = 1;
pub const TLS_INFO_CIPHER: _bindgen_ty_1 = 2;
pub const TLS_INFO_TXCONF: _bindgen_ty_1 = 3;
pub const TLS_INFO_RXCONF: _bindgen_ty_1 = 4;
pub const TLS_INFO_ZC_RO_TX: _bindgen_ty_1 = 5;
pub const TLS_INFO_RX_NO_PAD: _bindgen_ty_1 = 6;
pub const TLS_INFO_TX_MAX_PAYLOAD_LEN: _bindgen_ty_1 = 7;
pub const __TLS_INFO_MAX: _bindgen_ty_1 = 8;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
