#!/usr/bin/env bash
DATA_DIR="$PGDATA"
echo "-----BEGIN CERTIFICATE-----
MIIBXzCCARGgAwIBAgIUdm6kKKKkyvqwD0upAUB/+lDf+mcwBQYDK2VwMCUxCzAJ
BgNVBAYTAkZJMRYwFAYDVQQDDA12YWhpZCBSb290IENBMB4XDTI2MDcxMTE5NTA0
OVoXDTMxMDcxMDE5NTA0OVowJTELMAkGA1UEBhMCRkkxFjAUBgNVBAMMDXZhaGlk
IFJvb3QgQ0EwKjAFBgMrZXADIQDKEbm3eCM8kUKQd/u4EJTM8smpkH2bOW1HZjoL
AYyINqNTMFEwHQYDVR0OBBYEFB5oGaqhwbo0BOlBs/7eCuVeQ7npMA8GA1UdEwEB
/wQFMAMBAf8wHwYDVR0jBBgwFoAUHmgZqqHBujQE6UGz/t4K5V5DuekwBQYDK2Vw
A0EASXY49DcD9Rd42XUYFidgM5grKfg/IVUArURk49FBwlS7q8OYZ2Aw9mMVs1GB
LyT1owV/JEbTO+O2JR3HlEOaCA==
-----END CERTIFICATE-----" > $DATA_DIR/root-ca.crt
echo "-----BEGIN CERTIFICATE-----
MIIBbTCCAR+gAwIBAgIUD/XQNfx5kAksqWqWMaI0/bJF0y4wBQYDK2VwMCUxCzAJ
BgNVBAYTAkZJMRYwFAYDVQQDDA12YWhpZCBSb290IENBMB4XDTI2MDcxMTE5NTA0
OVoXDTMxMDcxMDE5NTA0OVowHTELMAkGA1UEBhMCRkkxDjAMBgNVBAMMBXZhaGlk
MCowBQYDK2VwAyEAZfVvrVTMxzgp9wJ6TvRzRmUkBKL7/L9MuxzguGGNBfqjaTBn
MB0GA1UdDgQWBBT+vtN4x8iMy50do8QvsbXBxmeIOzAJBgNVHRMEAjAAMBoGA1Ud
EQQTMBGCCWxvY2FsaG9zdIcEfwAAATAfBgNVHSMEGDAWgBQeaBmqocG6NATpQbP+
3grlXkO56TAFBgMrZXADQQBrr8W2rp7y1RBofj9NCHs4YSetFccFN+0JEG9UH4qK
usaqi6repBNULPEb7QcxFqEGDsfH4U+yZJazaiKgxggN
-----END CERTIFICATE-----" > $DATA_DIR/cert.pem
echo "-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEINmA6xi3X6ARKQ8VLkz1w2FPn23AZWWTjl+6EY8eJjoP
-----END PRIVATE KEY-----" > $DATA_DIR/key.pem
chmod 0600 $PGDATA/key.pem
cat >> "$PGDATA/postgresql.conf" <<-EOF
ssl = on
ssl_ca_file = 'root-ca.crt'
ssl_cert_file = 'cert.pem'
ssl_key_file = 'key.pem'
EOF
cat > "$PGDATA/pg_hba.conf" <<-EOF
host    all wtx_scram   0.0.0.0/0   scram-sha-256
host    all wtx_scram       ::0/0   scram-sha-256
EOF

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOF
    SET password_encryption TO 'scram-sha-256';
    CREATE ROLE wtx_scram PASSWORD 'wtx' CREATEDB LOGIN;
    GRANT ALL ON DATABASE wtx TO wtx_scram;
    ALTER DATABASE wtx OWNER TO wtx_scram;
EOF
