#!/usr/bin/env bash
DATA_DIR="$PGDATA"
echo "-----BEGIN CERTIFICATE-----
MIIBTzCCAQGgAwIBAgIUDjSIVbSeUHXb4saiZjxgYYxde9owBQYDK2VwMB0xCzAJ
BgNVBAYTAkZJMQ4wDAYDVQQDDAV2YWhpZDAeFw0yNjA3MDYyMTE1MDJaFw0zMTA3
MDUyMTE1MDJaMB0xCzAJBgNVBAYTAkZJMQ4wDAYDVQQDDAV2YWhpZDAqMAUGAytl
cAMhAOB5QUA/jcRStfTJRNdD7VCqJB96WNnalgK20oTNCmtNo1MwUTAdBgNVHQ4E
FgQUveY3HoXfto75/EPSPUoOQ2lZ3dcwHwYDVR0jBBgwFoAUveY3HoXfto75/EPS
PUoOQ2lZ3dcwDwYDVR0TAQH/BAUwAwEB/zAFBgMrZXADQQDt8Wt8UAJgX7pVhH2G
ErRS4ZGltvWHb5mBcV1Zh8OLLt6RlkOX3hC1Bb603SOtUqCG9DrE1fdm8jLcaamh
XoEC
-----END CERTIFICATE-----" > $DATA_DIR/root-ca.crt
echo "-----BEGIN CERTIFICATE-----
MIIBZTCCARegAwIBAgIUGyACrBkQf+9xFvRtKBCbuxahYAowBQYDK2VwMB0xCzAJ
BgNVBAYTAkZJMQ4wDAYDVQQDDAV2YWhpZDAeFw0yNjA3MDYyMTE1MDJaFw0zMTA3
MDUyMTE1MDJaMB0xCzAJBgNVBAYTAkZJMQ4wDAYDVQQDDAV2YWhpZDAqMAUGAytl
cAMhABbm4YhLVAmGIL+n4qrD8BjevxxrAgmnmHiWv7iH6BQ8o2kwZzAfBgNVHSME
GDAWgBS95jcehd+2jvn8Q9I9Sg5DaVnd1zAJBgNVHRMEAjAAMBoGA1UdEQQTMBGC
CWxvY2FsaG9zdIcEfwAAATAdBgNVHQ4EFgQUU4xVyyj64q6s2EP3zRr+vcCuUqww
BQYDK2VwA0EAdmZe9C0qnG9ROI+fkOkEVCcPfSg0QfUo/GR2bd6WWTwmZp8oT+hf
ovt6Mn7CjTvzffqTx0OvWVxOxgit0D/dDQ==
-----END CERTIFICATE-----" > $DATA_DIR/cert.pem
echo "-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIKCH5Uj5jiM8UTLbtRVxc4Loehk1PJxdqLzJNFc/ReB2
-----END PRIVATE KEY-----" > $DATA_DIR/key.pem
chmod 0600 $PGDATA/key.pem
cat >> "$PGDATA/postgresql.conf" <<-EOF
ssl = on
ssl_ca_file = 'root-ca.crt'
ssl_cert_file = 'cert.pem'
ssl_key_file = 'key.pem'
EOF
cat > "$PGDATA/pg_hba.conf" <<-EOF
host    all wtx_scram   0.0.0.0/0   scram-sha-256
host    all wtx_scram       ::0/0   scram-sha-256
EOF

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOF
    SET password_encryption TO 'scram-sha-256';
    CREATE ROLE wtx_scram PASSWORD 'wtx' CREATEDB LOGIN;
    GRANT ALL ON DATABASE wtx TO wtx_scram;
    ALTER DATABASE wtx OWNER TO wtx_scram;
EOF
