[[bin]]
name = "datetime"
path = "datetime.rs"
required-features = ["libfuzzer-sys/link_libfuzzer"]

[dependencies]
libfuzzer-sys = { default-features = false, version = "0.4" }
wtx = { default-features = false, features = ["arbitrary", "web-socket"], path = "../wtx" }

[package]
edition = "2024"
name = "wtx-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true
