create_enum! {
  #[derive(Clone, Copy, Debug, PartialEq)]
  pub(crate) enum Command<u8> {
    ComSleep = (0),
    ComQuit = (1),
    ComInitDb = (2),
    ComQuery = (3),
    ComFieldList = (4),
    ComCreateDb = (5),
    ComDropDb = (6),
    ComRefresh = (7),
    ComDeprecated1 = (8),
    ComStatistics = (9),
    ComProcessInfo = (10),
    ComConnect = (11),
    ComProcessKill = (12),
    ComDebug = (13),
    ComPing = (14),
    ComTime = (15),
    ComDelayedInsert = (16),
    ComChangeUser = (17),
    ComBinlogDump = (18),
    ComTableDump = (19),
    ComConnectOut = (20),
    ComRegisterSlave = (21),
    ComStmtPrepare = (22),
    ComStmtExecute = (23),
    ComStmtSendLongData = (24),
    ComStmtClose = (25),
    ComStmtReset = (26),
    ComSetOption = (27),
    ComStmtFetch = (28),
    ComDaemon = (29),
    ComBinlogDumpGtid = (30),
    ComResetConnection = (31),
    ComEnd = (32),
  }
}
