name: Bencher

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  benchmark_with_bencher:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
            --adapter rust_bench \
            --branch main \
            --err \
            --project wtx \
            --testbed ubuntu-latest \
            --token "${{ secrets.BENCHER_API_TOKEN }}" \
            "cargo bench --all-features"