name: 'Supply chain'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cargo-vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.10.2
    steps:
    - uses: actions/checkout@master
    - run: rustup update stable && rustup default stable
    - uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/cargo-vet
        key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
    - run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
    - run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
    - run: cargo vet --locked --store-path wtx-supply-chain/
